# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CS Grad Council
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Computer Science Graduate Council at Virginia Tech
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://csgrad.cs.vt.edu" # the base hostname & protocol for your site, e.g. http://example.com
main_pages:
  - url: "/meetings/"
    title: "Contact and Meeting Info"
  - url: "/events/"
    title: "Events"
  - url: "/resources/"
    title: "Resources"
  - url: "/covid/"
    title: "COVID-19 Information"
  - url: "/travel_funding/"
    title: "Travel Funding"
  - url: "/officers/"
    title: "Officers"
  - url: "/housing/"
    title: "Housing"
  - url: "/lab_representatives/"
    title: "Lab Representatives"
  - url: "/checklist/"
    title: "Graduate Student Checklist"
  - url: "https://groups.google.com/a/vt.edu/g/csgc-g"
    title: "Mailing List and Group"
  - url: "https://drive.google.com/drive/folders/0B0b9Zb_kmZenbG1VTnhadTNHVDg?resourcekey=0-R5zlmZwPMfdvFHt6VbvUvw&usp=sharing"
    title: "Resources"
twitter_username:
github_username:

# Build settings
markdown: kramdown
theme: jekyll-theme-hyde
plugins:
  - jekyll-feed
version: 0.0.1
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
