name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.1
    - run: bundle install
    - run: bundle exec jekyll build -d _site/
    
    # Runs a single command using the runners shell
    - name: Zip the Website
      run: zip -r ${{ github.workspace }}/Website.zip _site 
  
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: Update_${{ github.sha }}
        release_name: Update_${{ github.sha }}
        body: Release_${{ github.sha }}

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ${{ github.workspace }}/Website.zip
        asset_name: Website.zip
        asset_content_type: application/zip
