name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.1

    #Fixing the bundle issue noted here: https://bundler.io/blog/2019/01/04/an-update-on-the-bundler-2-release.html
    - run: gem install bundler -v 2.1.4
    - run: bundle install
    - run: bundle exec jekyll build -d _site/
    
    # Runs a single command using the runners shell
    - name: Zip the Website
      run: zip -r ${{ github.workspace }}/Website.zip _site 

    - name: Get Time
      id: time
      uses: nanzm/get-time-action@v1.0
      with:
        format: 'YYYY-MM-DD-HH-mm'
  
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: Update_${{ steps.time.outputs.time }}
        release_name: Update_${{ steps.time.outputs.time }}
        body: Update_${{ steps.time.outputs.time }}

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ${{ github.workspace }}/Website.zip
        asset_name: Website.zip
        asset_content_type: application/zip
